from argparse import ArgumentParser
from trimesh import PointCloud, load
from camera import (
    CameraExtrinsic,
    CameraIntrinsic,
    load_camera_intrinsics,
    load_camera_extrinsics,
    calc_w2c,
    load_point_cloud,
    project_points_to_camera,
)
import numpy as np


def parse_args():
    parser = ArgumentParser(description="Post-process point cloud generated by VGGT")
    parser.add_argument("--input", type=str, required=True, help="Input file folder")
    parser.add_argument(
        "--output", type=str, required=True, help="Output PLY file path"
    )
    parser.add_argument(
        "--data_root",
        type=str,
        default="/data/yzr/Final",
        help="Root directory of all scenes",
    )
    parser.add_argument(
        "--id", type=str, default="1750383597053", help="ID of the scene"
    )

    return parser.parse_args()


"""Documents from VGGT
pose_encoding (torch.Tensor): Encoded camera pose parameters with shape Sx9,
    where S is sequence length.
    For "absT_quaR_FoV" type, the 9 dimensions are:
    - [:3] = absolute translation vector T (3D)
    - [3:7] = rotation as quaternion quat (4D)
    - [7:] = field of view (2D)

extrinsics (torch.Tensor): Camera extrinsic parameters with shape Sx3x4.
    In OpenCV coordinate system (x-right, y-down, z-forward), representing camera from world
    transformation. The format is [R|t] where R is a 3x3 rotation matrix and t is
    a 3x1 translation vector.
"""


def compute_similarity_error(
    P, Q, scale, R, t, error_type="rmse", return_details=False
):
    """
    计算相似变换的拟合误差

    参数:
        P: numpy数组, shape (N, 3), 源点云
        Q: numpy数组, shape (N, 3), 目标点云
        scale: float, 缩放因子
        R: numpy数组, shape (3, 3), 旋转矩阵
        t: numpy数组, shape (3,), 平移向量
        error_type: str, 误差类型
            - 'rmse': 均方根误差 (默认)
            - 'mae': 平均绝对误差
            - 'max': 最大误差
            - 'normalized': 标准化RMSE (相对于点云直径)
        return_details: bool, 是否返回详细误差信息

    返回:
        error: float, 标量误差值
        details: dict, 当return_details=True时返回详细信息
    """
    # 输入验证
    if P.shape != Q.shape:
        raise ValueError("点云P和Q必须具有相同的形状")
    if P.shape[0] == 0:
        raise ValueError("点云不能为空")

    # 应用变换: Q_pred = scale * (P @ R.T) + t
    Q_pred = scale * (P @ R.T) + t

    # 计算逐点误差 (欧氏距离)
    per_point_errors = np.linalg.norm(Q - Q_pred, axis=1)

    # 计算各种误差度量
    rmse = np.sqrt(np.mean(per_point_errors**2))
    mae = np.mean(per_point_errors)
    max_error = np.max(per_point_errors)

    # 标准化RMSE (相对于目标点云的直径)
    # diameter = sqrt(max(||q_i - q_j||^2))，这里用更稳定的std近似
    q_std = np.std(Q, axis=0).mean()
    normalized_rmse = rmse / (q_std + 1e-8)

    # 根据error_type返回结果
    error_map = {
        "rmse": rmse,
        "mae": mae,
        "max": max_error,
        "normalized": normalized_rmse,
    }

    if error_type not in error_map:
        raise ValueError(
            f"不支持的error_type: {error_type}. 可选值: {list(error_map.keys())}"
        )

    error = error_map[error_type]

    if return_details:
        details = {
            "rmse": rmse,
            "mae": mae,
            "max_error": max_error,
            "normalized_rmse": normalized_rmse,
            "per_point_errors": per_point_errors,
            "mean_q_pred": np.mean(Q_pred, axis=0),
            "std_q_pred": np.std(Q_pred, axis=0),
            "mean_q_target": np.mean(Q, axis=0),
            "std_q_target": np.std(Q, axis=0),
        }
        return error, details

    return error


def similarity_transform(P, Q, estimate_scale=True):
    """
    计算两个点云之间的相似变换（刚体变换 + 均匀缩放）

    参数:
        P: (N, 3) 源点云
        Q: (N, 3) 目标点云
        estimate_scale: 是否估计缩放（若为False，则s=1）

    返回:
        scale: 缩放因子 (标量)
        R: (3, 3) 旋转矩阵
        t: (3,) 平移向量

    变换公式: Q = scale * (P @ R.T) + t
    """
    # 1. 输入验证
    if P.shape != Q.shape or P.shape[0] < 3:
        raise ValueError("点云形状不匹配或点数不足")

    # 2. 计算质心
    mu_p = np.mean(P, axis=0)
    mu_q = np.mean(Q, axis=0)

    # 3. 中心化
    P_centered = P - mu_p
    Q_centered = Q - mu_q

    # 4. 协方差矩阵
    H = P_centered.T @ Q_centered  # (3, 3)

    # 5. SVD分解
    U, s_vals, Vt = np.linalg.svd(H)

    # 6. 处理反射（核心修正）
    S = np.eye(3)
    if np.linalg.det(Vt.T @ U.T) < 0:
        S[2, 2] = -1

    R = Vt.T @ S @ U.T  # 确保det(R)=1

    # 7. 缩放因子
    if estimate_scale:
        # 使用奇异值之和更稳定
        scale = np.sum(s_vals * np.diag(S)) / np.trace(P_centered.T @ P_centered)
    else:
        scale = 1.0

    # 8. 平移
    t = mu_q - scale * (R @ mu_p)

    return scale, R, t


def main():
    args = parse_args()
    ROOT = args.data_root
    ID = args.id
    VIDEO_INFO_FILE = f"{ROOT}/{ID}/inputs/videoInfo.txt"
    OUT_FILE = args.output

    extrins, qs, ts = load_camera_extrinsics(f"{ROOT}/{ID}/inputs/slam/images.txt")
    intrin = load_camera_intrinsics(f"{ROOT}/{ID}/inputs/slam/cameras.txt")
    id, xyz, rgb = load_point_cloud(f"{ROOT}/{ID}/inputs/slam/points3D.txt")

    pc_vggt: PointCloud = load(f"{args.input}/{ID}.ply")
    extrin_from_vggt = np.load(f"{args.input}/{ID}_extrins.npy")
    intrin_from_vggt = np.load(f"{args.input}/{ID}_intris.npy")

    pose_enc_from_vggt = np.load(f"{args.input}/{ID}_pose_enc.npy")
    ts_vggt = pose_enc_from_vggt[:, :3]
    qs_vggt = pose_enc_from_vggt[:, 3:7]

    scale, R, t = similarity_transform(ts_vggt, ts)
    print(scale, R, t)
    print(compute_similarity_error(
        ts_vggt, ts,
        scale, R, t
    ))

    # # Put the vggt point cloud into original
    pc_vggt_transformed = scale * (np.array(pc_vggt.vertices) @ R.T) + t
    pc_vggt_color = np.array(pc_vggt.colors).astype(np.float32) / 255.0

    print(pc_vggt_transformed.shape, pc_vggt_color.shape) # (n, 3) (n, 4)
    print(xyz.shape, rgb.shape) # (n, 3) (n, 3)

    # Concatenate and export a larger point cloud
    pc_combined = np.concatenate([xyz, pc_vggt_transformed], axis=0)
    rgb_combined = np.concatenate([rgb, pc_vggt_color[:, :3]], axis=0)
    pc = PointCloud(pc_combined, colors=rgb_combined)
    pc.export(str(OUT_FILE))

if __name__ == '__main__':
    main()